---
- hosts: all
  become: yes
  tasks:
    - name: apache2
      apt:
        name: apache2
        state: present
     - name: i want to install webserver on nodes
        service: 
        name: apache2
        state: started
        

