---
- hosts: mywebservers
  become: yes
  tasks:
  - name: Install Java on Ubuntu nodes
    apt:
      name: "{{ java_package_name_ubuntu }}"
      state: present
    when: ansible_os_family == "Debian"

  - name: Install Java on Red Hat nodes
    dnf:
      name: "{{ java_package_name_redhat }}"
      state: present
    when: ansible_os_family == "Redhat"
<<<<<<< HEAD

=======
>>>>>>> 778eb241607c0cf818e5ab77a24c54e9eb5f7f2f
