---
- hosts: 173.30.0.9
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: Install webserver server
      apt:
        name: apache2
        state: present

    - name: Copy static files into the node side
      copy:
        src: /path/to/your/staticfiles
        dest: /home/ubuntu/
        remote_src: yes
    - name: download internet file
      get_url:
        url: http://example.com/path/file.conf  
        dest: /home/ubuntu/https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        force_basic_auth: yes