---
- hosts: 173.30.0.9
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver server
    apt:
      name: apache2
      state: present
  - name: copy static file into the node side
    copy:
      src: staticfiles
      dest: /home/ubuntu/staticfiles