---
- hosts: 173.30.0.9
  become: yes
  tasks:
    - name: Include tasks from myfile.yml
      include_tasks: myfile.yml

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Copy static files to the node
      copy:
        src: mystaticfiles
        dest: /home/ubuntu/mystaticfiles

    - name: Download internet file (Tomcat)
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
        force_basic_auth: yes

    - name: Copy index file to node
      template:
        src: myindex.j2
        dest: /var/www/html/index.html
      notify: restart apache service

  handlers:
    - name: restart apache service
      service:
        name: apache2
        state: restarted
