---
- hosts: 173.30.0.9
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: Install webserver server
      apt:
        name: apache2
        state: present

    - name: Copy static files into the node side
      copy:
        src: staticfiles
        dest: /home/ubuntu/
        remote_src: yes
