---
- hosts: mywebservers
  become: yes
  tasks:
    - name: Install Apache on Debian systems
      apt:
        name: "{{ myapacheubunutu }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Apache on Debian systems
      service:
        name: "{{ myapacheubunutu }}"
        state: started
      when: ansible_os_family == "Debian"

    - name: Install web server on Red Hat
      dnf:
        name: "{{ mywebredhat }}"
        state: present
      when: ansible_os_family == "Redhat"

    - name: Start web server on Red Hat
      service:
        name: "{{ mywebredhat }}"
        state: started
      when: ansible_os_family == "Redhat"

    - name: Start Nginx on Ubuntu 18.04
      service:
        name: "{{ mynginxubuntu }}"
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

    - name: Start web server on Red Hat nodes
      service:
        name: "{{ mynginxredhat }}"
        state: present
      when: ansible_os_family == "Redhat"

