---
- name: download tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
    force_basic_auth: yes

- name: extract tar file
  become: yes  # Add this line to run the command with sudo
  shell:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1 --wildcards 'apache-tomcat-*tar.gz'
    creates: /opt/tomcat/LICENSE
